part of 'm3e_navigation_rail_theme.dart';

/// Grouped field resolution shared by [M3ENavigationRailTheme.copyWith] and
/// [M3ENavigationRailTheme.lerp], split out so no single function grows
/// past the component length guidelines.
typedef _RailStructureOverrides = ({
  double collapsedWidth,
  double narrowCollapsedWidth,
  double collapsedHorizontalPadding,
  double narrowHorizontalPadding,
  double expandedMinWidth,
  double expandedMaxWidth,
  double itemExpandedHeight,
  double itemCollapsedHeight,
  double shortItemHeight,
  double iconSize,
  double indicatorLeading,
  double indicatorTrailing,
  double expandedItemInset,
  double iconLabelGap,
  double verticalIconLabelGap,
  double itemVerticalGap,
  double expandedItemGap,
  double itemVerticalPadding,
  double topSpace,
  double destinationTopPadding,
  double expandedTrailingSpace,
  double headerMinSpace,
  double sectionHeaderSpacingTop,
  double sectionHeaderSpacingBottom,
  double verticalIndicatorWidth,
  double verticalIndicatorHeight,
  double verticalIndicatorRadius,
  double expandedIndicatorHeight,
  double expandedIndicatorRadius,
  double noLabelIndicatorSize,
});

typedef _RailVisualOverrides = ({
  Color? containerColor,
  Color? modalContainerColor,
  Color? scrolledContainerColor,
  Color? activeIndicatorColor,
  Color? activeIconAndLabel,
  Color? activeLabelColor,
  Color? inactiveIconAndLabel,
  Color? menuColor,
  Color? badgeBackground,
  Color? badgeLargeLabel,
  Color? stateLayerColor,
  Color? focusRingColor,
  Color? dividerColor,
  ShapeBorder? indicatorShapeFull,
  bool indicatorFillsWidth,
  double elevation,
  double scrolledElevation,
  double modalScrimOpacity,
  double containerRadius,
  double modalContainerRadius,
  double dividerThickness,
  double hoverOpacity,
  double focusOpacity,
  double pressedOpacity,
  double focusRingThickness,
  double focusRingInset,
  double labelFontSize,
  double labelLineHeight,
  double labelLetterSpacing,
  FontWeight inactiveLabelWeight,
  FontWeight activeLabelWeight,
  int scaledLabelMaxLines,
  double truncationTextScale,
  M3ESpring indicatorLeadSpring,
  M3ESpring indicatorTrailSpring,
  M3ESpring indicatorScaleSpring,
  M3ESpring indicatorFadeSpring,
  M3ESpring iconScaleSpring,
  M3ESpring widthSpring,
});

/// Extension holding the private helpers for
/// [M3ENavigationRailTheme.copyWith] and [M3ENavigationRailTheme.lerp].
extension _M3ENavigationRailThemeCopy on M3ENavigationRailTheme {
  M3ENavigationRailTheme _copyNavigationRailTheme({
    double? collapsedWidth,
    double? narrowCollapsedWidth,
    double? collapsedHorizontalPadding,
    double? narrowHorizontalPadding,
    double? expandedMinWidth,
    double? expandedMaxWidth,
    double? itemExpandedHeight,
    double? itemCollapsedHeight,
    double? shortItemHeight,
    double? iconSize,
    double? indicatorLeading,
    double? indicatorTrailing,
    double? expandedItemInset,
    double? iconLabelGap,
    double? verticalIconLabelGap,
    double? itemVerticalGap,
    double? expandedItemGap,
    double? itemVerticalPadding,
    double? topSpace,
    double? destinationTopPadding,
    double? expandedTrailingSpace,
    double? headerMinSpace,
    double? sectionHeaderSpacingTop,
    double? sectionHeaderSpacingBottom,
    double? verticalIndicatorWidth,
    double? verticalIndicatorHeight,
    double? verticalIndicatorRadius,
    double? expandedIndicatorHeight,
    double? expandedIndicatorRadius,
    double? noLabelIndicatorSize,
    Color? containerColor,
    Color? modalContainerColor,
    Color? scrolledContainerColor,
    Color? activeIndicatorColor,
    Color? activeIconAndLabel,
    Color? activeLabelColor,
    Color? inactiveIconAndLabel,
    Color? menuColor,
    Color? badgeBackground,
    Color? badgeLargeLabel,
    Color? stateLayerColor,
    Color? focusRingColor,
    Color? dividerColor,
    ShapeBorder? indicatorShapeFull,
    bool? indicatorFillsWidth,
    double? elevation,
    double? scrolledElevation,
    double? modalScrimOpacity,
    double? containerRadius,
    double? modalContainerRadius,
    double? dividerThickness,
    double? hoverOpacity,
    double? focusOpacity,
    double? pressedOpacity,
    double? focusRingThickness,
    double? focusRingInset,
    double? labelFontSize,
    double? labelLineHeight,
    double? labelLetterSpacing,
    FontWeight? inactiveLabelWeight,
    FontWeight? activeLabelWeight,
    int? scaledLabelMaxLines,
    double? truncationTextScale,
    M3ESpring? indicatorLeadSpring,
    M3ESpring? indicatorTrailSpring,
    M3ESpring? indicatorScaleSpring,
    M3ESpring? indicatorFadeSpring,
    M3ESpring? iconScaleSpring,
    M3ESpring? widthSpring,
  }) {
    return _finishRailCopy(
      _resolveRailStructure(
        collapsedWidth: collapsedWidth,
        narrowCollapsedWidth: narrowCollapsedWidth,
        collapsedHorizontalPadding: collapsedHorizontalPadding,
        narrowHorizontalPadding: narrowHorizontalPadding,
        expandedMinWidth: expandedMinWidth,
        expandedMaxWidth: expandedMaxWidth,
        itemExpandedHeight: itemExpandedHeight,
        itemCollapsedHeight: itemCollapsedHeight,
        shortItemHeight: shortItemHeight,
        iconSize: iconSize,
        indicatorLeading: indicatorLeading,
        indicatorTrailing: indicatorTrailing,
        expandedItemInset: expandedItemInset,
        iconLabelGap: iconLabelGap,
        verticalIconLabelGap: verticalIconLabelGap,
        itemVerticalGap: itemVerticalGap,
        expandedItemGap: expandedItemGap,
        itemVerticalPadding: itemVerticalPadding,
        topSpace: topSpace,
        destinationTopPadding: destinationTopPadding,
        expandedTrailingSpace: expandedTrailingSpace,
        headerMinSpace: headerMinSpace,
        sectionHeaderSpacingTop: sectionHeaderSpacingTop,
        sectionHeaderSpacingBottom: sectionHeaderSpacingBottom,
        verticalIndicatorWidth: verticalIndicatorWidth,
        verticalIndicatorHeight: verticalIndicatorHeight,
        verticalIndicatorRadius: verticalIndicatorRadius,
        expandedIndicatorHeight: expandedIndicatorHeight,
        expandedIndicatorRadius: expandedIndicatorRadius,
        noLabelIndicatorSize: noLabelIndicatorSize,
      ),
      containerColor: containerColor,
      modalContainerColor: modalContainerColor,
      scrolledContainerColor: scrolledContainerColor,
      activeIndicatorColor: activeIndicatorColor,
      activeIconAndLabel: activeIconAndLabel,
      activeLabelColor: activeLabelColor,
      inactiveIconAndLabel: inactiveIconAndLabel,
      menuColor: menuColor,
      badgeBackground: badgeBackground,
      badgeLargeLabel: badgeLargeLabel,
      stateLayerColor: stateLayerColor,
      focusRingColor: focusRingColor,
      dividerColor: dividerColor,
      indicatorShapeFull: indicatorShapeFull,
      indicatorFillsWidth: indicatorFillsWidth,
      elevation: elevation,
      scrolledElevation: scrolledElevation,
      modalScrimOpacity: modalScrimOpacity,
      containerRadius: containerRadius,
      modalContainerRadius: modalContainerRadius,
      dividerThickness: dividerThickness,
      hoverOpacity: hoverOpacity,
      focusOpacity: focusOpacity,
      pressedOpacity: pressedOpacity,
      focusRingThickness: focusRingThickness,
      focusRingInset: focusRingInset,
      labelFontSize: labelFontSize,
      labelLineHeight: labelLineHeight,
      labelLetterSpacing: labelLetterSpacing,
      inactiveLabelWeight: inactiveLabelWeight,
      activeLabelWeight: activeLabelWeight,
      scaledLabelMaxLines: scaledLabelMaxLines,
      truncationTextScale: truncationTextScale,
      indicatorLeadSpring: indicatorLeadSpring,
      indicatorTrailSpring: indicatorTrailSpring,
      indicatorScaleSpring: indicatorScaleSpring,
      indicatorFadeSpring: indicatorFadeSpring,
      iconScaleSpring: iconScaleSpring,
      widthSpring: widthSpring,
    );
  }

  M3ENavigationRailTheme _finishRailCopy(
    _RailStructureOverrides structure, {
    Color? containerColor,
    Color? modalContainerColor,
    Color? scrolledContainerColor,
    Color? activeIndicatorColor,
    Color? activeIconAndLabel,
    Color? activeLabelColor,
    Color? inactiveIconAndLabel,
    Color? menuColor,
    Color? badgeBackground,
    Color? badgeLargeLabel,
    Color? stateLayerColor,
    Color? focusRingColor,
    Color? dividerColor,
    ShapeBorder? indicatorShapeFull,
    bool? indicatorFillsWidth,
    double? elevation,
    double? scrolledElevation,
    double? modalScrimOpacity,
    double? containerRadius,
    double? modalContainerRadius,
    double? dividerThickness,
    double? hoverOpacity,
    double? focusOpacity,
    double? pressedOpacity,
    double? focusRingThickness,
    double? focusRingInset,
    double? labelFontSize,
    double? labelLineHeight,
    double? labelLetterSpacing,
    FontWeight? inactiveLabelWeight,
    FontWeight? activeLabelWeight,
    int? scaledLabelMaxLines,
    double? truncationTextScale,
    M3ESpring? indicatorLeadSpring,
    M3ESpring? indicatorTrailSpring,
    M3ESpring? indicatorScaleSpring,
    M3ESpring? indicatorFadeSpring,
    M3ESpring? iconScaleSpring,
    M3ESpring? widthSpring,
  }) {
    return _assembleRailTheme(
      structure,
      _resolveRailVisuals(
        containerColor: containerColor,
        modalContainerColor: modalContainerColor,
        scrolledContainerColor: scrolledContainerColor,
        activeIndicatorColor: activeIndicatorColor,
        activeIconAndLabel: activeIconAndLabel,
        activeLabelColor: activeLabelColor,
        inactiveIconAndLabel: inactiveIconAndLabel,
        menuColor: menuColor,
        badgeBackground: badgeBackground,
        badgeLargeLabel: badgeLargeLabel,
        stateLayerColor: stateLayerColor,
        focusRingColor: focusRingColor,
        dividerColor: dividerColor,
        indicatorShapeFull: indicatorShapeFull,
        indicatorFillsWidth: indicatorFillsWidth,
        elevation: elevation,
        scrolledElevation: scrolledElevation,
        modalScrimOpacity: modalScrimOpacity,
        containerRadius: containerRadius,
        modalContainerRadius: modalContainerRadius,
        dividerThickness: dividerThickness,
        hoverOpacity: hoverOpacity,
        focusOpacity: focusOpacity,
        pressedOpacity: pressedOpacity,
        focusRingThickness: focusRingThickness,
        focusRingInset: focusRingInset,
        labelFontSize: labelFontSize,
        labelLineHeight: labelLineHeight,
        labelLetterSpacing: labelLetterSpacing,
        inactiveLabelWeight: inactiveLabelWeight,
        activeLabelWeight: activeLabelWeight,
        scaledLabelMaxLines: scaledLabelMaxLines,
        truncationTextScale: truncationTextScale,
        indicatorLeadSpring: indicatorLeadSpring,
        indicatorTrailSpring: indicatorTrailSpring,
        indicatorScaleSpring: indicatorScaleSpring,
        indicatorFadeSpring: indicatorFadeSpring,
        iconScaleSpring: iconScaleSpring,
        widthSpring: widthSpring,
      ),
    );
  }

  _RailStructureOverrides _resolveRailStructure({
    double? collapsedWidth,
    double? narrowCollapsedWidth,
    double? collapsedHorizontalPadding,
    double? narrowHorizontalPadding,
    double? expandedMinWidth,
    double? expandedMaxWidth,
    double? itemExpandedHeight,
    double? itemCollapsedHeight,
    double? shortItemHeight,
    double? iconSize,
    double? indicatorLeading,
    double? indicatorTrailing,
    double? expandedItemInset,
    double? iconLabelGap,
    double? verticalIconLabelGap,
    double? itemVerticalGap,
    double? expandedItemGap,
    double? itemVerticalPadding,
    double? topSpace,
    double? destinationTopPadding,
    double? expandedTrailingSpace,
    double? headerMinSpace,
    double? sectionHeaderSpacingTop,
    double? sectionHeaderSpacingBottom,
    double? verticalIndicatorWidth,
    double? verticalIndicatorHeight,
    double? verticalIndicatorRadius,
    double? expandedIndicatorHeight,
    double? expandedIndicatorRadius,
    double? noLabelIndicatorSize,
  }) {
    return (
      collapsedWidth: collapsedWidth ?? this.collapsedWidth,
      narrowCollapsedWidth: narrowCollapsedWidth ?? this.narrowCollapsedWidth,
      collapsedHorizontalPadding:
          collapsedHorizontalPadding ?? this.collapsedHorizontalPadding,
      narrowHorizontalPadding:
          narrowHorizontalPadding ?? this.narrowHorizontalPadding,
      expandedMinWidth: expandedMinWidth ?? this.expandedMinWidth,
      expandedMaxWidth: expandedMaxWidth ?? this.expandedMaxWidth,
      itemExpandedHeight: itemExpandedHeight ?? this.itemExpandedHeight,
      itemCollapsedHeight: itemCollapsedHeight ?? this.itemCollapsedHeight,
      shortItemHeight: shortItemHeight ?? this.shortItemHeight,
      iconSize: iconSize ?? this.iconSize,
      indicatorLeading: indicatorLeading ?? this.indicatorLeading,
      indicatorTrailing: indicatorTrailing ?? this.indicatorTrailing,
      expandedItemInset: expandedItemInset ?? this.expandedItemInset,
      iconLabelGap: iconLabelGap ?? this.iconLabelGap,
      verticalIconLabelGap: verticalIconLabelGap ?? this.verticalIconLabelGap,
      itemVerticalGap: itemVerticalGap ?? this.itemVerticalGap,
      expandedItemGap: expandedItemGap ?? this.expandedItemGap,
      itemVerticalPadding: itemVerticalPadding ?? this.itemVerticalPadding,
      topSpace: topSpace ?? this.topSpace,
      destinationTopPadding:
          destinationTopPadding ?? this.destinationTopPadding,
      expandedTrailingSpace:
          expandedTrailingSpace ?? this.expandedTrailingSpace,
      headerMinSpace: headerMinSpace ?? this.headerMinSpace,
      sectionHeaderSpacingTop:
          sectionHeaderSpacingTop ?? this.sectionHeaderSpacingTop,
      sectionHeaderSpacingBottom:
          sectionHeaderSpacingBottom ?? this.sectionHeaderSpacingBottom,
      verticalIndicatorWidth:
          verticalIndicatorWidth ?? this.verticalIndicatorWidth,
      verticalIndicatorHeight:
          verticalIndicatorHeight ?? this.verticalIndicatorHeight,
      verticalIndicatorRadius:
          verticalIndicatorRadius ?? this.verticalIndicatorRadius,
      expandedIndicatorHeight:
          expandedIndicatorHeight ?? this.expandedIndicatorHeight,
      expandedIndicatorRadius:
          expandedIndicatorRadius ?? this.expandedIndicatorRadius,
      noLabelIndicatorSize: noLabelIndicatorSize ?? this.noLabelIndicatorSize,
    );
  }

  _RailVisualOverrides _resolveRailVisuals({
    Color? containerColor,
    Color? modalContainerColor,
    Color? scrolledContainerColor,
    Color? activeIndicatorColor,
    Color? activeIconAndLabel,
    Color? activeLabelColor,
    Color? inactiveIconAndLabel,
    Color? menuColor,
    Color? badgeBackground,
    Color? badgeLargeLabel,
    Color? stateLayerColor,
    Color? focusRingColor,
    Color? dividerColor,
    ShapeBorder? indicatorShapeFull,
    bool? indicatorFillsWidth,
    double? elevation,
    double? scrolledElevation,
    double? modalScrimOpacity,
    double? containerRadius,
    double? modalContainerRadius,
    double? dividerThickness,
    double? hoverOpacity,
    double? focusOpacity,
    double? pressedOpacity,
    double? focusRingThickness,
    double? focusRingInset,
    double? labelFontSize,
    double? labelLineHeight,
    double? labelLetterSpacing,
    FontWeight? inactiveLabelWeight,
    FontWeight? activeLabelWeight,
    int? scaledLabelMaxLines,
    double? truncationTextScale,
    M3ESpring? indicatorLeadSpring,
    M3ESpring? indicatorTrailSpring,
    M3ESpring? indicatorScaleSpring,
    M3ESpring? indicatorFadeSpring,
    M3ESpring? iconScaleSpring,
    M3ESpring? widthSpring,
  }) {
    return (
      containerColor: containerColor ?? this.containerColor,
      modalContainerColor: modalContainerColor ?? this.modalContainerColor,
      scrolledContainerColor:
          scrolledContainerColor ?? this.scrolledContainerColor,
      activeIndicatorColor: activeIndicatorColor ?? this.activeIndicatorColor,
      activeIconAndLabel: activeIconAndLabel ?? this.activeIconAndLabel,
      activeLabelColor: activeLabelColor ?? this.activeLabelColor,
      inactiveIconAndLabel: inactiveIconAndLabel ?? this.inactiveIconAndLabel,
      menuColor: menuColor ?? this.menuColor,
      badgeBackground: badgeBackground ?? this.badgeBackground,
      badgeLargeLabel: badgeLargeLabel ?? this.badgeLargeLabel,
      stateLayerColor: stateLayerColor ?? this.stateLayerColor,
      focusRingColor: focusRingColor ?? this.focusRingColor,
      dividerColor: dividerColor ?? this.dividerColor,
      indicatorShapeFull: indicatorShapeFull ?? this.indicatorShapeFull,
      indicatorFillsWidth: indicatorFillsWidth ?? this.indicatorFillsWidth,
      elevation: elevation ?? this.elevation,
      scrolledElevation: scrolledElevation ?? this.scrolledElevation,
      modalScrimOpacity: modalScrimOpacity ?? this.modalScrimOpacity,
      containerRadius: containerRadius ?? this.containerRadius,
      modalContainerRadius: modalContainerRadius ?? this.modalContainerRadius,
      dividerThickness: dividerThickness ?? this.dividerThickness,
      hoverOpacity: hoverOpacity ?? this.hoverOpacity,
      focusOpacity: focusOpacity ?? this.focusOpacity,
      pressedOpacity: pressedOpacity ?? this.pressedOpacity,
      focusRingThickness: focusRingThickness ?? this.focusRingThickness,
      focusRingInset: focusRingInset ?? this.focusRingInset,
      labelFontSize: labelFontSize ?? this.labelFontSize,
      labelLineHeight: labelLineHeight ?? this.labelLineHeight,
      labelLetterSpacing: labelLetterSpacing ?? this.labelLetterSpacing,
      inactiveLabelWeight: inactiveLabelWeight ?? this.inactiveLabelWeight,
      activeLabelWeight: activeLabelWeight ?? this.activeLabelWeight,
      scaledLabelMaxLines: scaledLabelMaxLines ?? this.scaledLabelMaxLines,
      truncationTextScale: truncationTextScale ?? this.truncationTextScale,
      indicatorLeadSpring: indicatorLeadSpring ?? this.indicatorLeadSpring,
      indicatorTrailSpring: indicatorTrailSpring ?? this.indicatorTrailSpring,
      indicatorScaleSpring: indicatorScaleSpring ?? this.indicatorScaleSpring,
      indicatorFadeSpring: indicatorFadeSpring ?? this.indicatorFadeSpring,
      iconScaleSpring: iconScaleSpring ?? this.iconScaleSpring,
      widthSpring: widthSpring ?? this.widthSpring,
    );
  }

  M3ENavigationRailTheme _assembleRailTheme(
    _RailStructureOverrides structure,
    _RailVisualOverrides visuals,
  ) {
    return M3ENavigationRailTheme(
      collapsedWidth: structure.collapsedWidth,
      narrowCollapsedWidth: structure.narrowCollapsedWidth,
      collapsedHorizontalPadding: structure.collapsedHorizontalPadding,
      narrowHorizontalPadding: structure.narrowHorizontalPadding,
      expandedMinWidth: structure.expandedMinWidth,
      expandedMaxWidth: structure.expandedMaxWidth,
      itemExpandedHeight: structure.itemExpandedHeight,
      itemCollapsedHeight: structure.itemCollapsedHeight,
      shortItemHeight: structure.shortItemHeight,
      iconSize: structure.iconSize,
      indicatorLeading: structure.indicatorLeading,
      indicatorTrailing: structure.indicatorTrailing,
      expandedItemInset: structure.expandedItemInset,
      iconLabelGap: structure.iconLabelGap,
      verticalIconLabelGap: structure.verticalIconLabelGap,
      itemVerticalGap: structure.itemVerticalGap,
      expandedItemGap: structure.expandedItemGap,
      itemVerticalPadding: structure.itemVerticalPadding,
      topSpace: structure.topSpace,
      destinationTopPadding: structure.destinationTopPadding,
      expandedTrailingSpace: structure.expandedTrailingSpace,
      headerMinSpace: structure.headerMinSpace,
      sectionHeaderSpacingTop: structure.sectionHeaderSpacingTop,
      sectionHeaderSpacingBottom: structure.sectionHeaderSpacingBottom,
      verticalIndicatorWidth: structure.verticalIndicatorWidth,
      verticalIndicatorHeight: structure.verticalIndicatorHeight,
      verticalIndicatorRadius: structure.verticalIndicatorRadius,
      expandedIndicatorHeight: structure.expandedIndicatorHeight,
      expandedIndicatorRadius: structure.expandedIndicatorRadius,
      noLabelIndicatorSize: structure.noLabelIndicatorSize,
      containerColor: visuals.containerColor,
      modalContainerColor: visuals.modalContainerColor,
      scrolledContainerColor: visuals.scrolledContainerColor,
      activeIndicatorColor: visuals.activeIndicatorColor,
      activeIconAndLabel: visuals.activeIconAndLabel,
      activeLabelColor: visuals.activeLabelColor,
      inactiveIconAndLabel: visuals.inactiveIconAndLabel,
      menuColor: visuals.menuColor,
      badgeBackground: visuals.badgeBackground,
      badgeLargeLabel: visuals.badgeLargeLabel,
      stateLayerColor: visuals.stateLayerColor,
      focusRingColor: visuals.focusRingColor,
      dividerColor: visuals.dividerColor,
      indicatorShapeFull: visuals.indicatorShapeFull,
      indicatorFillsWidth: visuals.indicatorFillsWidth,
      elevation: visuals.elevation,
      scrolledElevation: visuals.scrolledElevation,
      modalScrimOpacity: visuals.modalScrimOpacity,
      containerRadius: visuals.containerRadius,
      modalContainerRadius: visuals.modalContainerRadius,
      dividerThickness: visuals.dividerThickness,
      hoverOpacity: visuals.hoverOpacity,
      focusOpacity: visuals.focusOpacity,
      pressedOpacity: visuals.pressedOpacity,
      focusRingThickness: visuals.focusRingThickness,
      focusRingInset: visuals.focusRingInset,
      labelFontSize: visuals.labelFontSize,
      labelLineHeight: visuals.labelLineHeight,
      labelLetterSpacing: visuals.labelLetterSpacing,
      inactiveLabelWeight: visuals.inactiveLabelWeight,
      activeLabelWeight: visuals.activeLabelWeight,
      scaledLabelMaxLines: visuals.scaledLabelMaxLines,
      truncationTextScale: visuals.truncationTextScale,
      indicatorLeadSpring: visuals.indicatorLeadSpring,
      indicatorTrailSpring: visuals.indicatorTrailSpring,
      indicatorScaleSpring: visuals.indicatorScaleSpring,
      indicatorFadeSpring: visuals.indicatorFadeSpring,
      iconScaleSpring: visuals.iconScaleSpring,
      widthSpring: visuals.widthSpring,
    );
  }
}
